.TH PEV 1
.SH NAME
pev - shows version number of MS-DOS/Windows executables
.SH SYNOPSIS
.B pev
.IR file ...
.SH DESCRIPTION
Shows the Product Version number (if added by programmer) of MS-DOS/Windows PE32 (Portable Executable) files such EXE or DLL.
.TP
.BR \-h ", " \-\-help
Show usage and exit.
.TP
.BR \-v ", " \-\-version
Show version and exit.
.SH AUTHOR
Written by Eduardo Fernandes, Fernando Mercês, Francivan Bezerra and Thiago Moraes.
.SH REPORTING BUGS
Report pev bugs to coding40@mentebinaria.com.br
.SH COPYRIGHT
Copyright © 2010 Coding 40°. Licensed GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
