# This script was generated by crazy-complete.
# crazy-complete: A tool that creates robust and reliable autocompletion scripts for Bash, Fish and Zsh.
# For more information, visit: https://github.com/crazy-complete/crazy-complete

_readpe__exec() {
  local item desc special="$COMP_WORDBREAKS\"'><=;|&({:\\\$\`"

  while IFS=$'\t' read -r item desc; do
    if [[ "$item" == "$cur"* ]]; then
      [[ "$item" == *[$special]* ]] && item="$(printf '%q' "$item")"
      COMPREPLY+=("$item")
    fi
  done < <(eval "$1")
}

_readpe__prefix_compreply() {
  [[ "$cur" == *[$COMP_WORDBREAKS]* ]] && return

  local i prefix="$1"
  for ((i=0; i < ${#COMPREPLY[@]}; ++i)); do
    COMPREPLY[i]="$prefix${COMPREPLY[i]}"
  done
}

_readpe__dequote_words() {
  local word dequoted break_pos in_quotes

  words_dequoted=()

  for word in "${words[@]}"; do
    _readpe__dequote "$word" dequoted break_pos in_quotes
    words_dequoted+=("$dequoted")
  done
}

_readpe__dequote() {
  local in="$1" len=${#1} i=0 result='' ___break_pos=-1 ___in_quotes=0

  for ((; i < len; ++i)); do
    case "${in:i:1}" in
      "'")
        ___in_quotes=1
        for ((++i; i < len; ++i)); do
          [[ "${in:i:1}" == "'" ]] && { ___in_quotes=0; break; }
          result+="${in:i:1}"
        done;;
      '"')
        ___in_quotes=1
        for ((++i; i < len; ++i)); do
          [[ "${in:i:1}" == '"' ]] && { ___in_quotes=0; break; }

          if [[ "${in:i:1}" == '\' ]]; then
            result+="${in:$((++i)):1}"
          else
            result+="${in:i:1}"
          fi
        done;;
      '\')
        result+="${in:$((++i)):1}";;
      [$COMP_WORDBREAKS])
        result+="${in:i:1}"
        ___break_pos=${#result};;
      *)
        result+="${in:i:1}";;
    esac
  done

  local -n ___RESULT=$2
  local -n ___BREAK_POS=$3
  local -n ___IN_QUOTES=$4
  ___RESULT="$result"
  ___BREAK_POS=$___break_pos
  ___IN_QUOTES=$___in_quotes
}

_readpe__parse_commandline() {
  POSITIONALS=()
  END_OF_OPTIONS=0

  local cmd="root" argi arg i char trailing_chars VAR ARGS

  __find_option() {
    case "$1" in root:hash)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:scan)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
        -V|--version) VAR=OPT_version; ARGS=0; return;;
      esac
    esac
    case "$1" in root:section:hash)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:section)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
        -a|--all) VAR=OPT_all; ARGS=0; return;;
        -l|--list) VAR=OPT_list; ARGS=0; return;;
        -i|--index) VAR=OPT_index; ARGS=1; return;;
        -n|--name) VAR=OPT_name; ARGS=1; return;;
      esac
    esac
    case "$1" in root:security)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:features)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:certificates)
      case "$2" in
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -o|--out) VAR=OPT_out; ARGS=0; return;;
        -V|--version) VAR=OPT_version; ARGS=0; return;;
      esac
    esac
    case "$1" in root:resources:extract)
      case "$2" in
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -n|--named) VAR=OPT_named; ARGS=0; return;;
        -V|--version) VAR=OPT_version; ARGS=0; return;;
      esac
    esac
    case "$1" in root:resources)
      case "$2" in
        --file-version) VAR=OPT_file_version; ARGS=0; return;;
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -l|--list) VAR=OPT_list; ARGS=0; return;;
        -s|--statistics) VAR=OPT_statistics; ARGS=0; return;;
        -t|--tree) VAR=OPT_tree; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
        -V|--version) VAR=OPT_version; ARGS=0; return;;
      esac
    esac
    case "$1" in root:imports)
      case "$2" in
        -a|--all) VAR=OPT_all; ARGS=0; return;;
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -l|--list) VAR=OPT_list; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
        -V|--version) VAR=OPT_version; ARGS=0; return;;
      esac
    esac
    case "$1" in root:exports)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:directories)
      case "$2" in
        -a|--all) VAR=OPT_all; ARGS=0; return;;
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -l|--list) VAR=OPT_list; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
        -V|--version) VAR=OPT_version; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header:hash)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header:optional:hash)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header:optional)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header:coff:hash)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header:coff)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header:dos:hash)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header:dos)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
      esac
    esac
    case "$1" in root:header)
      case "$2" in
        -a|--all) VAR=OPT_all; ARGS=0; return;;
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -l|--list) VAR=OPT_list; ARGS=0; return;;
        -v|--verbose) VAR=OPT_verbose; ARGS=0; return;;
        -V|--version) VAR=OPT_version; ARGS=0; return;;
      esac
    esac
    case "$1" in root)
      case "$2" in
        -f|--format) VAR=OPT_format; ARGS=1; return;;
        --file-version) VAR=OPT_file_version; ARGS=0; return;;
        -h|--help) VAR=OPT_help; ARGS=0; return;;
        -v|--version) VAR=OPT_version; ARGS=0; return;;
        --get-output-plugins) VAR=OPT_get_output_plugins; ARGS=0; return;;
      esac
    esac
    return 1
  }

  __append_to_array() {
    local -n arr=$1
    arr+=("$2")
  }

  for ((argi=1; argi < cword; ++argi)); do
    arg="${words_dequoted[argi]}"

    case "$arg" in
      --)
        END_OF_OPTIONS=1
        POSITIONALS+=("${words_dequoted[@]:$((++argi))}")
        return;;
      --*=*)
        if __find_option "$cmd" "${arg%%=*}"
        then __append_to_array "$VAR" "${arg#*=}"
        fi;;
      --*)
        if __find_option "$cmd" "$arg"; then
          if [[ "$ARGS" == 1 ]]
          then __append_to_array "$VAR" "${words_dequoted[++argi]}"
          else __append_to_array "$VAR" "_OPT_ISSET_"
          fi
        fi;;
      -?*) # ignore '-'

        for ((i=1; i < ${#arg}; ++i)); do
          char="${arg:$i:1}"
          trailing_chars="${arg:$((i + 1))}"

          if __find_option "$cmd" "-$char"; then
            if [[ "$ARGS" == 1 ]]; then
              if [[ -n "$trailing_chars" ]]
              then __append_to_array "$VAR" "$trailing_chars"
              else __append_to_array "$VAR" "${words_dequoted[++argi]}"
              fi
              break;
            else
              __append_to_array "$VAR" "_OPT_ISSET_"
            fi
          fi
        done
        ;;
      *)
        POSITIONALS+=("$arg")
        case "$cmd|${#POSITIONALS[@]}" in
          'root|2') cmd+=":$arg";;
          'root:header|3') cmd+=":$arg";;
          'root:header:dos|4') cmd+=":$arg";;
          'root:header:coff|4') cmd+=":$arg";;
          'root:header:optional|4') cmd+=":$arg";;
          'root:resources|3') cmd+=":$arg";;
          'root:section|4') cmd+=":$arg";;
        esac
        ;;
    esac
  done

  for ((; argi <= cword; ++argi)); do
    case "${words_dequoted[argi]}" in
      -?*);;
      *) POSITIONALS+=("${words_dequoted[argi]}");;
    esac
  done
}

_readpe() {
  local cur prev words cword split words_dequoted
  _init_completion -n =: || return
  _readpe__dequote_words

  local END_OF_OPTIONS POSITIONALS
  local -a OPT_format OPT_file_version OPT_help OPT_version
  local -a OPT_get_output_plugins OPT_all OPT_list OPT_verbose OPT_statistics
  local -a OPT_tree OPT_named OPT_out OPT_index OPT_name
  _readpe__parse_commandline

  if (( 1 < ${#POSITIONALS[@]} )); then
    case "${POSITIONALS[1]}" in
      header) _readpe_header && return 0 || return 1;;
      directories) _readpe_directories && return 0 || return 1;;
      exports) _readpe_exports && return 0 || return 1;;
      imports) _readpe_imports && return 0 || return 1;;
      resources) _readpe_resources && return 0 || return 1;;
      certificates) _readpe_certificates && return 0 || return 1;;
      features) _readpe_features && return 0 || return 1;;
      security) _readpe_security && return 0 || return 1;;
      section) _readpe_section && return 0 || return 1;;
      scan) _readpe_scan && return 0 || return 1;;
      hash) _readpe_hash && return 0 || return 1;;
    esac
  fi

  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(--file-version -h --help -v --version)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  (( ${#POSITIONALS[@]} == 1 )) && {
    _filedir
    return 0;
  }

  (( ${#POSITIONALS[@]} == 2 )) && {
    COMPREPLY=($(compgen -W 'header directories exports imports resources certificates features security section scan hash' -- "$cur"))
    return 0;
  }

  return 1
}

_readpe_header() {
  if (( 2 < ${#POSITIONALS[@]} )); then
    case "${POSITIONALS[2]}" in
      dos) _readpe_header_dos && return 0 || return 1;;
      coff) _readpe_header_coff && return 0 || return 1;;
      optional) _readpe_header_optional && return 0 || return 1;;
      hash) _readpe_header_hash && return 0 || return 1;;
    esac
  fi

  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([ahlvV])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([ahlvV])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_all[@]} )) && opts+=(-a --all)
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose -V --version)
      (( ! ${#OPT_list[@]} )) && opts+=(-l --list)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  (( ${#POSITIONALS[@]} == 3 )) && {
    COMPREPLY=($(compgen -W 'dos coff optional hash' -- "$cur"))
    return 0;
  }

  return 1
}

_readpe_header_dos() {
  if (( 3 < ${#POSITIONALS[@]} )); then
    case "${POSITIONALS[3]}" in
      hash) _readpe_header_dos_hash && return 0 || return 1;;
    esac
  fi

  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  (( ${#POSITIONALS[@]} == 4 )) && {
    COMPREPLY=($(compgen -W hash -- "$cur"))
    return 0;
  }

  return 1
}

_readpe_header_dos_hash() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_header_coff() {
  if (( 3 < ${#POSITIONALS[@]} )); then
    case "${POSITIONALS[3]}" in
      hash) _readpe_header_coff_hash && return 0 || return 1;;
    esac
  fi

  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  (( ${#POSITIONALS[@]} == 4 )) && {
    COMPREPLY=($(compgen -W hash -- "$cur"))
    return 0;
  }

  return 1
}

_readpe_header_coff_hash() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_header_optional() {
  if (( 3 < ${#POSITIONALS[@]} )); then
    case "${POSITIONALS[3]}" in
      hash) _readpe_header_optional_hash && return 0 || return 1;;
    esac
  fi

  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  (( ${#POSITIONALS[@]} == 4 )) && {
    COMPREPLY=($(compgen -W hash -- "$cur"))
    return 0;
  }

  return 1
}

_readpe_header_optional_hash() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_header_hash() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_directories() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([ahlvV])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([ahlvV])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_all[@]} )) && opts+=(-a --all)
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose -V --version)
      (( ! ${#OPT_list[@]} )) && opts+=(-l --list)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_exports() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_imports() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([ahlvV])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([ahlvV])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_all[@]} )) && opts+=(-a --all)
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose -V --version)
      (( ! ${#OPT_list[@]} )) && opts+=(-l --list)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_resources() {
  if (( 2 < ${#POSITIONALS[@]} )); then
    case "${POSITIONALS[2]}" in
      extract) _readpe_resources_extract && return 0 || return 1;;
    esac
  fi

  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hlstvV])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hlstvV])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      opts+=(--file-version -h --help -v --verbose -V --version)
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      (( ! ${#OPT_list[@]} )) && opts+=(-l --list)
      (( ! ${#OPT_statistics[@]} )) && opts+=(-s --statistics)
      (( ! ${#OPT_tree[@]} )) && opts+=(-t --tree)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  (( ${#POSITIONALS[@]} == 3 )) && {
    COMPREPLY=($(compgen -W extract -- "$cur"))
    return 0;
  }

  return 1
}

_readpe_resources_extract() {
  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      opts+=(-h --help -V --version)
      (( ! ${#OPT_named[@]} )) && opts+=(-n --named)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_certificates() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        COMPREPLY=($(compgen -W 'x509 pem der' -- "$cur"));;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hoV])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hoV])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      opts+=(-h --help -V --version)
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      (( ! ${#OPT_out[@]} )) && opts+=(-o --out)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_features() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_security() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_section() {
  if (( 3 < ${#POSITIONALS[@]} )); then
    case "${POSITIONALS[3]}" in
      hash) _readpe_section_hash && return 0 || return 1;;
    esac
  fi

  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      -i|--index)
        COMPREPLY=($(compgen -W @1 -- "$cur"));;
      -n|--name)
        COMPREPLY=($(compgen -W .text -- "$cur"));;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hval])[fin])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hval])[fin]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
      (( ! ${#OPT_all[@]} )) && opts+=(-a --all)
      (( ! ${#OPT_list[@]} )) && opts+=(-l --list)
      (( ! ${#OPT_index[@]} )) && opts+=(-i --index=)
      (( ! ${#OPT_name[@]} )) && opts+=(-n --name=)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  (( ${#POSITIONALS[@]} == 3 )) && {
    _readpe__exec 'readpe $READPE section --list'
    return 0;
  }

  (( ${#POSITIONALS[@]} == 4 )) && {
    COMPREPLY=($(compgen -W hash -- "$cur"))
    return 0;
  }

  return 1
}

_readpe_section_hash() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_scan() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hvV])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hvV])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_version[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose -V --version)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

_readpe_hash() {
  __complete_option() {
    local opt="$1" cur="$2" ret=0

    case "$opt" in
      -f|--format)
        _readpe__exec 'readpe --get-output-plugins';;
      *) ret=1;;
    esac

    return $ret
  }

  case "$prev" in
    --*) __complete_option "$prev" "$cur" && return 0;;
    -*([hv])[f])
         __complete_option "-${prev: -1}" "$cur" && return 0;;
  esac

  case "$cur" in
    --*=*)
      __complete_option "${cur%%=*}" "${cur#*=}" && return 0;;
    --*);;
    -*([hv])[f]*)
      local i
      for ((i=2; i <= ${#cur}; ++i)); do
        local pre="${cur:0:$i}" value="${cur:$i}"
        __complete_option "-${pre: -1}" "$value" && {
          _readpe__prefix_compreply "$pre"
          return 0
        }
      done;;
  esac

  if (( ! END_OF_OPTIONS )) && [[ "$cur" = -* ]]; then
    local -a opts
    if (( ! ${#OPT_help[@]} && ! ${#OPT_verbose[@]} && ! ${#OPT_file_version[@]} && ! ${#OPT_help[@]} && ! ${#OPT_version[@]} && ! ${#OPT_get_output_plugins[@]} )); then
      (( ! ${#OPT_format[@]} )) && opts+=(-f --format=)
      opts+=(-h --help -v --verbose)
    fi
    COMPREPLY+=($(compgen -W "${opts[*]}" -- "$cur"))
    [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
    return 1
  fi

  return 1
}

complete -F _readpe readpe

# vim: ft=sh ts=2 sts=2 sw=2 et
