#compdef readpe

# This script was generated by crazy-complete.
# crazy-complete: A tool that creates robust and reliable autocompletion scripts for Bash, Fish and Zsh.
# For more information, visit: https://github.com/crazy-complete/crazy-complete

_readpe__query() {

  __zsh_query_contains() {
    local arg='' key="$1"; shift
    for arg; do [[ "$key" == "$arg" ]] && return 0; done
    return 1
  }

  local cmd="$1"; shift

  case "$cmd" in
    get_positional)
      printf "%s" "${POSITIONALS[$1]}"
      return 0;;
    init)
      local -a options=(${=1})
      shift;;
    *)
      echo "_readpe__query: argv[1]: invalid command" >&2
      return 1;;
  esac


  local  long_opts_with_arg=()  long_opts_with_optional_arg=()  long_opts_without_arg=()
  local short_opts_with_arg=() short_opts_with_optional_arg=() short_opts_without_arg=()

  local option=''
  for option in "${options[@]}"; do
    case "$option" in
      --?*=)    long_opts_with_arg+=("${option%=}");;
      --?*=\?)  long_opts_with_optional_arg+=("${option%=?}");;
      --?*)     long_opts_without_arg+=("$option");;
      -?=)      short_opts_with_arg+=("${option%=}");;
      -?=\?)    short_opts_with_optional_arg+=("${option%=?}");;
      -?)       short_opts_without_arg+=("$option");;
    esac
  done

  POSITIONALS=()
  HAVING_OPTIONS=()
  OPTION_VALUES=()
  INCOMPLETE_OPTION=''

  local args=("${(Q)@}")
  local argi=2 # argi[1] is program name
  for ((; argi <= ${#args[@]}; ++argi)); do
    local arg="${args[$argi]}"
    local have_trailing_arg=$(test $argi -lt $# && echo true || echo false)

    case "$arg" in
      --)
        POSITIONALS+=("${@:$((argi + 1))}")
        break;;
      --*=*)
        HAVING_OPTIONS+=("${arg%%=*}")
        OPTION_VALUES+=("${arg#*=}");;
      --*)
        if __zsh_query_contains "$arg" "${long_opts_with_arg[@]}"; then
          if $have_trailing_arg; then
            HAVING_OPTIONS+=("$arg")
            OPTION_VALUES+=("${args[$((++argi))]}")
          fi
        else
          HAVING_OPTIONS+=("$arg")
          OPTION_VALUES+=("")
        fi
        ;;
      -?*) # ignore '-'

        local i=1 arg_length=${#arg}
        for ((; i < arg_length; ++i)); do
          local option="-${arg:$i:1}"
          local trailing_chars="${arg:$((i+1))}"

          if __zsh_query_contains "$option" "${short_opts_without_arg[@]}"; then
            HAVING_OPTIONS+=("$option")
            OPTION_VALUES+=("")
          elif __zsh_query_contains "$option" "${short_opts_with_arg[@]}"; then
            if [[ -n "$trailing_chars" ]]; then
              HAVING_OPTIONS+=("$option")
              OPTION_VALUES+=("$trailing_chars")
            elif $have_trailing_arg; then
              HAVING_OPTIONS+=("$option")
              OPTION_VALUES+=("${args[$((++argi))]}")
            fi

            continue 2
          elif __zsh_query_contains "$option" "${short_opts_with_optional_arg[@]}"; then
            HAVING_OPTIONS+=("$option")
            OPTION_VALUES+=("$trailing_chars") # may be empty
            continue 2
          fi
        done
        ;;
      *)
        POSITIONALS+=("$arg");;
    esac
  done
}

_readpe__exec() {
  local item='' desc='' describe=()

  while IFS=$'\t' read -r item desc; do
    item="${item//:/\\:}"
    [[ -n "$desc" ]] && describe+=("$item:$desc") || describe+=("$item")
  done < <(eval "$1")

  _describe '' describe
}

_readpe__command() {
  local items=(
    header
    directories
    exports
    imports
    resources
    certificates
    features
    security
    section
    scan
    hash
  )

  _describe -- command items
}

_readpe() {
  local opts='-f= --format= --file-version -h --help -v --version --get-output-plugins'
  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
  _readpe__query init "$opts" "${words[@]}"

  case "$(_readpe__query get_positional 2)" in
    header) _readpe_header; return $?;;
    directories) _readpe_directories; return $?;;
    exports) _readpe_exports; return $?;;
    imports) _readpe_imports; return $?;;
    resources) _readpe_resources; return $?;;
    certificates) _readpe_certificates; return $?;;
    features) _readpe_features; return $?;;
    security) _readpe_security; return $?;;
    section) _readpe_section; return $?;;
    scan) _readpe_scan; return $?;;
    hash) _readpe_hash; return $?;;
  esac

  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'--file-version'[Show PE file version]'
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--version}'[Print program version]'
    '!''(- *)'--get-output-plugins'[Print available output plugins]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header() {
  local opts='-a --all -f= --format= -h --help -l --list -v --verbose -V --version --file-version -v --version --get-output-plugins'
  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
  _readpe__query init "$opts" "${words[@]}"

  case "$(_readpe__query get_positional 3)" in
    dos) _readpe_header_dos; return $?;;
    coff) _readpe_header_coff; return $?;;
    optional) _readpe_header_optional; return $?;;
    hash) _readpe_header_hash; return $?;;
  esac

  local -a args=(
    '(--all -a)'{-a,--all}'[Print all headers]'
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(--list -l)'{-l,--list}'[Print list of present headers]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    '(- *)'{-V,--version}'[Print program version]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header_dos() {
  local opts='-f= --format= -h --help -v --verbose -a --all -l --list -V --version --file-version -v --version --get-output-plugins'
  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
  _readpe__query init "$opts" "${words[@]}"

  case "$(_readpe__query get_positional 4)" in
    hash) _readpe_header_dos_hash; return $?;;
  esac

  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
    4:command3:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header_dos_hash() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
    4:command3:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header_coff() {
  local opts='-f= --format= -h --help -v --verbose -a --all -l --list -V --version --file-version -v --version --get-output-plugins'
  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
  _readpe__query init "$opts" "${words[@]}"

  case "$(_readpe__query get_positional 4)" in
    hash) _readpe_header_coff_hash; return $?;;
  esac

  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
    4:command3:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header_coff_hash() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
    4:command3:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header_optional() {
  local opts='-f= --format= -h --help -v --verbose -a --all -l --list -V --version --file-version -v --version --get-output-plugins'
  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
  _readpe__query init "$opts" "${words[@]}"

  case "$(_readpe__query get_positional 4)" in
    hash) _readpe_header_optional_hash; return $?;;
  esac

  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
    4:command3:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header_optional_hash() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
    4:command3:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_header_hash() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((dos coff optional hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_directories() {
  local -a args=(
    '(--all -a)'{-a,--all}'[Print all headers]'
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(--list -l)'{-l,--list}'[Print list of present headers]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    '(- *)'{-V,--version}'[Print program version]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_exports() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_imports() {
  local -a args=(
    '(--all -a)'{-a,--all}'[Print all headers]'
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(--list -l)'{-l,--list}'[Print list of present headers]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    '(- *)'{-V,--version}'[Print program version]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_resources() {
  local opts='--file-version -f= --format= -h --help -l --list -s --statistics -t --tree -v --verbose -V --version -v --version --get-output-plugins'
  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
  _readpe__query init "$opts" "${words[@]}"

  case "$(_readpe__query get_positional 3)" in
    extract) _readpe_resources_extract; return $?;;
  esac

  local -a args=(
    '(- *)'--file-version'[Show PE file version]'
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(--list -l)'{-l,--list}'[Print list of present headers]'
    '(--statistics -s)'{-s,--statistics}'[Print resources statistics]'
    '(--tree -t)'{-t,--tree}'[Prints resources as a directory tree]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    '(- *)'{-V,--version}'[Print program version]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((extract))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_resources_extract() {
  local -a args=(
    '(- *)'{-h,--help}'[Print this message]'
    '(--named -n)'{-n,--named}'[Extracts resources with filenames]'
    '(- *)'{-V,--version}'[Print program version]'
    1:' ':_files
    2:command1:_readpe__command
    3:command2:'((extract))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_certificates() {
  local -a args=(
    '(- *)'{-h,--help}'[Print this message]'
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:'(x509 pem der)'
    '(--out -o)'{-o,--out}'[Set output filename]'
    '(- *)'{-V,--version}'[Print program version]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_features() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_security() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_section() {
  local opts='-f= --format= -h --help -v --verbose -a --all -l --list -i= --index= -n= --name= --file-version -v --version --get-output-plugins'
  local HAVING_OPTIONS=() OPTION_VALUES=() POSITIONALS=() INCOMPLETE_OPTION=''
  _readpe__query init "$opts" "${words[@]}"

  case "$(_readpe__query get_positional 4)" in
    hash) _readpe_section_hash; return $?;;
  esac

  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    '(--all -a)'{-a,--all}'[Print all headers]'
    '(--list -l)'{-l,--list}'[Print list of present headers]'
    '(--index -i)'{-i+,--index=}'[INDEX]':' ':'(@1)'
    '(--name -n)'{-n+,--name=}'[NAME]':' ':'(.text)'
    1:' ':_files
    2:command1:_readpe__command
    3:' ':"{_readpe__exec 'readpe \$READPE section --list'}"
    4:command2:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_section_hash() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
    3:' ':"{_readpe__exec 'readpe \$READPE section --list'}"
    4:command2:'((hash))'
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_scan() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    '(- *)'{-V,--version}'[Print program version]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe_hash() {
  local -a args=(
    '(--format -f)'{-f+,--format=}'[Set output format]':FORMAT:"{_readpe__exec 'readpe --get-output-plugins'}"
    '(- *)'{-h,--help}'[Print this message]'
    '(- *)'{-v,--verbose}'[Print more verbose]'
    1:' ':_files
    2:command1:_readpe__command
  )
  _arguments -S -s -w "${args[@]}"
}

_readpe "$@"

# vim: ft=zsh ts=2 sts=2 sw=2 et
