# This script was generated by crazy-complete.
# crazy-complete: A tool that creates robust and reliable autocompletion scripts for Bash, Fish and Zsh.
# For more information, visit: https://github.com/crazy-complete/crazy-complete

function _readpe__query

  set -l positionals
  set -l having_options
  set -l option_values

  set -l options $argv[1]
  set -e argv[1]

  set -l cmd $argv[1]
  set -e argv[1]

  set -l my_cache_key "$(commandline -b) $options"

  if test "$__QUERY_CACHE_KEY" = "$my_cache_key"
    set positionals    $__QUERY_CACHE_POSITIONALS
    set having_options $__QUERY_CACHE_HAVING_OPTIONS
    set option_values  $__QUERY_CACHE_OPTION_VALUES
  else

    set -l short_opts_with_arg
    set -l short_opts_without_arg
    set -l short_opts_with_optional_arg
    set -l long_opts_with_arg
    set -l long_opts_without_arg
    set -l long_opts_with_optional_arg

    set -l option

    if test -n "$options"
      for option in (string split -- ' ' $options)
        if false
          true
        else if string match -qr -- '^--.+=$' $option
          set -a long_opts_with_arg (string replace -- '=' '' $option)
        else if string match -qr -- '^--.+=\?$' $option
          set -a long_opts_with_optional_arg (string replace -- '=?' '' $option)
        else if string match -qr -- '^--.+$' $option
          set -a long_opts_without_arg $option
        else if string match -qr -- '^-.=$' $option
          set -a short_opts_with_arg (string replace -- '=' '' $option)
        else if string match -qr -- '^-.=\?$' $option
          set -a short_opts_with_optional_arg (string replace -- '=?' '' $option)
        else if string match -qr -- '^-.$' $option
          set -a short_opts_without_arg $option
        end
      end
    end

    set -l cmdline (commandline -poc)
    set -l cmdline_count (count $cmdline)

    set -l argi 2 # cmdline[1] is command name
    while test $argi -le $cmdline_count
      set -l arg "$cmdline[$argi]"
      set -l have_trailing_arg (test $argi -lt $cmdline_count && echo true || echo false)

      switch $arg
        case '-'
          set -a positionals -
        case '--'
          set -a positionals $cmdline[$(math $argi + 1)..]
          break
        case '--*=*'
          set -l split (string split -m 1 -- '=' $arg)
          set -a having_options $split[1]
          set -a option_values "$split[2]"
        case '--*'
          if contains -- $arg $long_opts_with_arg
            if $have_trailing_arg
              set -a having_options $arg
              set -a option_values $cmdline[(math $argi + 1)]
              set argi (math $argi + 1)
            end
          else
            set -a having_options $arg
            set -a option_values ''
          end
        case '-*'
          set -l end_of_parsing false

          set -l arg_length (string length -- $arg)
          set -l i 2
          while not $end_of_parsing; and test $i -le $arg_length
            set -l option "-$(string sub -s $i -l 1 -- $arg)"
            set -l trailing_chars "$(string sub -s (math $i + 1) -- $arg)"

            if contains -- $option $short_opts_without_arg
              set -a having_options $option
              set -a option_values ''
            else if contains -- $option $short_opts_with_arg
              set end_of_parsing true

              if test -n "$trailing_chars"
                set -a having_options $option
                set -a option_values $trailing_chars
              else if $have_trailing_arg
                set -a having_options $option
                set -a option_values $cmdline[(math $argi + 1)]
                set argi (math $argi + 1)
              end
            else if contains -- $option $short_opts_with_optional_arg
              set end_of_parsing true
              set -a having_options $option
              set -a option_values "$trailing_chars" # may be empty
            end

            set i (math $i + 1)
          end
        case '*'
          set -a positionals $arg
      end

      set argi (math $argi + 1)
    end

    set -g __QUERY_CACHE_POSITIONALS    $positionals
    set -g __QUERY_CACHE_HAVING_OPTIONS $having_options
    set -g __QUERY_CACHE_OPTION_VALUES  $option_values
    set -g __QUERY_CACHE_KEY            $my_cache_key
  end

  switch $cmd
    case 'positional_contains'
      set -l positional_num $argv[1]
      set -e argv[1]
      contains -- $positionals[$positional_num] $argv && return 0 || return 1
    case 'has_option'
      set -l with_incomplete false

      if test $argv[1] = 'WITH_INCOMPLETE'
        set with_incomplete true
        set -e argv[1]
      end

      for option in $having_options
        contains -- $option $argv && return 0
      end

      if $with_incomplete
        set -l tokens (commandline -po)
        set -e tokens[1]
        for option in $argv
          if test 2 -eq (string length -- $option)
            set option (string sub -l 1 -s 2 -- $option)
            string match -rq -- "^-[A-z0-9]*$option\$"   $tokens[-2] && return 0
            string match -rq -- "^-[A-z0-9]*$option.*\$" $tokens[-1] && return 0
          else
            string match -q -r -- "^$option\$"       $tokens[-2] && return 0
            string match -q -r -- "^$option(=.*)?\$" $tokens[-1] && return 0
            contains -- $tokens[-1] $argv && return 0
          end
        end
      end

      return 1
    case 'num_of_positionals'
      switch (count $argv)
        case 0
          count $positionals
        case 2
          if contains -- $argv[1] -lt -le -eq -ne -gt -ge;
            test (count $positionals) $argv[1] $argv[2] && return 0 || return 1
          end
      end
  end
end

function _readpe__command
  printf '%s\t%s\n' \
    header '' \
    directories '' \
    exports '' \
    imports '' \
    resources '' \
    certificates '' \
    features '' \
    security '' \
    section '' \
    scan '' \
    hash ''
end

set -l prog 'readpe'
set -l query '_readpe__query'

# Delete existing completions
complete -c $prog -e

# Generally disable file completion
complete -c $prog -x

# command readpe
set -l opts "-f= --format= --file-version -h --help -v --version --get-output-plugins"
set -l C000 "$query '$opts' num_of_positionals -eq 1 && not $query '$opts' has_option --file-version -h --help -v --version --get-output-plugins -f --format"
set -l C001 "$query '$opts' num_of_positionals -eq 1 && not $query '$opts' has_option --file-version -h --help -v --version --get-output-plugins"
set -l C002 "$query '$opts' num_of_positionals -eq 1 && $query '$opts' has_option WITH_INCOMPLETE --get-output-plugins && not $query '$opts' has_option --file-version -h --help -v --version --get-output-plugins"
set -l C003 "$query '$opts' num_of_positionals -eq 0"
set -l C004 "$query '$opts' num_of_positionals -eq 1"
complete -c $prog -n $C000 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C001 -l file-version -d 'Show PE file version' -f
complete -c $prog -n $C001 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s v -l version -d 'Print program version' -f
complete -c $prog -n $C002 -l get-output-plugins -d 'Print available output plugins' -f
complete -c $prog -n $C003 -Fr
complete -c $prog -n $C004 -d Commands -f -a '(_readpe__command)'

# command readpe header
set -l opts "-a --all -f= --format= -h --help -l --list -v --verbose -V --version --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 header && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -a --all"
set -l C001 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 header && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -f --format"
set -l C002 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 header && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins"
set -l C003 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 header && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -l --list"
set -l C004 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 header"
complete -c $prog -n $C000 -s a -l all -d 'Print all headers' -f
complete -c $prog -n $C001 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C002 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C003 -s l -l list -d 'Print list of present headers' -f
complete -c $prog -n $C002 -s v -l verbose -d 'Print more verbose' -f
complete -c $prog -n $C002 -s V -l version -d 'Print program version' -f
complete -c $prog -n $C004 -d Commands -f -a "dos\\t'' coff\\t'' optional\\t'' hash\\t''"

# command readpe directories
set -l opts "-a --all -f= --format= -h --help -l --list -v --verbose -V --version --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 directories && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -a --all"
set -l C001 "$query '$opts' positional_contains 2 directories && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -f --format"
set -l C002 "$query '$opts' positional_contains 2 directories && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins"
set -l C003 "$query '$opts' positional_contains 2 directories && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -l --list"
complete -c $prog -n $C000 -s a -l all -d 'Print all headers' -f
complete -c $prog -n $C001 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C002 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C003 -s l -l list -d 'Print list of present headers' -f
complete -c $prog -n $C002 -s v -l verbose -d 'Print more verbose' -f
complete -c $prog -n $C002 -s V -l version -d 'Print program version' -f

# command readpe exports
set -l opts "-f= --format= -h --help -v --verbose --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 exports && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -f --format"
set -l C001 "$query '$opts' positional_contains 2 exports && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins"
complete -c $prog -n $C000 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C001 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s v -l verbose -d 'Print more verbose' -f

# command readpe imports
set -l opts "-a --all -f= --format= -h --help -l --list -v --verbose -V --version --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 imports && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -a --all"
set -l C001 "$query '$opts' positional_contains 2 imports && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -f --format"
set -l C002 "$query '$opts' positional_contains 2 imports && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins"
set -l C003 "$query '$opts' positional_contains 2 imports && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -l --list"
complete -c $prog -n $C000 -s a -l all -d 'Print all headers' -f
complete -c $prog -n $C001 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C002 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C003 -s l -l list -d 'Print list of present headers' -f
complete -c $prog -n $C002 -s v -l verbose -d 'Print more verbose' -f
complete -c $prog -n $C002 -s V -l version -d 'Print program version' -f

# command readpe resources
set -l opts "--file-version -f= --format= -h --help -l --list -s --statistics -t --tree -v --verbose -V --version -v --version --get-output-plugins"
set -l C000 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 resources && not $query '$opts' has_option --file-version -h --help -v --verbose -V --version --get-output-plugins"
set -l C001 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 resources && not $query '$opts' has_option --file-version -h --help -v --verbose -V --version --get-output-plugins -f --format"
set -l C002 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 resources && not $query '$opts' has_option --file-version -h --help -v --verbose -V --version --get-output-plugins -l --list"
set -l C003 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 resources && not $query '$opts' has_option --file-version -h --help -v --verbose -V --version --get-output-plugins -s --statistics"
set -l C004 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 resources && not $query '$opts' has_option --file-version -h --help -v --verbose -V --version --get-output-plugins -t --tree"
set -l C005 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 resources"
complete -c $prog -n $C000 -l file-version -d 'Show PE file version' -f
complete -c $prog -n $C001 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C000 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C002 -s l -l list -d 'Print list of present headers' -f
complete -c $prog -n $C003 -s s -l statistics -d 'Print resources statistics' -f
complete -c $prog -n $C004 -s t -l tree -d 'Prints resources as a directory tree' -f
complete -c $prog -n $C000 -s v -l verbose -d 'Print more verbose' -f
complete -c $prog -n $C000 -s V -l version -d 'Print program version' -f
complete -c $prog -n $C005 -d Commands -f -a "extract\\t''"

# command readpe certificates
set -l opts "-h --help -f= --format= -o --out -V --version --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 certificates && not $query '$opts' has_option -h --help -V --version --file-version -v --get-output-plugins"
set -l C001 "$query '$opts' positional_contains 2 certificates && not $query '$opts' has_option -h --help -V --version --file-version -v --get-output-plugins -f --format"
set -l C002 "$query '$opts' positional_contains 2 certificates && not $query '$opts' has_option -h --help -V --version --file-version -v --get-output-plugins -o --out"
complete -c $prog -n $C000 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s f -l format -d 'Set output format' -x -a 'x509 pem der'
complete -c $prog -n $C002 -s o -l out -d 'Set output filename' -f
complete -c $prog -n $C000 -s V -l version -d 'Print program version' -f

# command readpe features
set -l opts "-f= --format= -h --help -v --verbose --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 features && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -f --format"
set -l C001 "$query '$opts' positional_contains 2 features && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins"
complete -c $prog -n $C000 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C001 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s v -l verbose -d 'Print more verbose' -f

# command readpe security
set -l opts "-f= --format= -h --help -v --verbose --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 security && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -f --format"
set -l C001 "$query '$opts' positional_contains 2 security && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins"
complete -c $prog -n $C000 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C001 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s v -l verbose -d 'Print more verbose' -f

# command readpe section
set -l opts "-f= --format= -h --help -v --verbose -a --all -l --list -i= --index= -n= --name= --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' num_of_positionals -eq 3 && $query '$opts' positional_contains 2 section && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -f --format"
set -l C001 "$query '$opts' num_of_positionals -eq 3 && $query '$opts' positional_contains 2 section && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins"
set -l C002 "$query '$opts' num_of_positionals -eq 3 && $query '$opts' positional_contains 2 section && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -a --all"
set -l C003 "$query '$opts' num_of_positionals -eq 3 && $query '$opts' positional_contains 2 section && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -l --list"
set -l C004 "$query '$opts' num_of_positionals -eq 3 && $query '$opts' positional_contains 2 section && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -i --index"
set -l C005 "$query '$opts' num_of_positionals -eq 3 && $query '$opts' positional_contains 2 section && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -n --name"
set -l C006 "$query '$opts' num_of_positionals -eq 2 && $query '$opts' positional_contains 2 section"
set -l C007 "$query '$opts' num_of_positionals -eq 3 && $query '$opts' positional_contains 2 section"
complete -c $prog -n $C000 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C001 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s v -l verbose -d 'Print more verbose' -f
complete -c $prog -n $C002 -s a -l all -d 'Print all headers' -f
complete -c $prog -n $C003 -s l -l list -d 'Print list of present headers' -f
complete -c $prog -n $C004 -s i -l index -d INDEX -x -a @1
complete -c $prog -n $C005 -s n -l name -d NAME -x -a .text
complete -c $prog -n $C006 -x -a '(readpe $READPE section --list)'
complete -c $prog -n $C007 -d Commands -f -a "hash\\t''"

# command readpe scan
set -l opts "-f= --format= -h --help -v --verbose -V --version --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 scan && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins -f --format"
set -l C001 "$query '$opts' positional_contains 2 scan && not $query '$opts' has_option -h --help -v --verbose -V --version --file-version --get-output-plugins"
complete -c $prog -n $C000 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C001 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s v -l verbose -d 'Print more verbose' -f
complete -c $prog -n $C001 -s V -l version -d 'Print program version' -f

# command readpe hash
set -l opts "-f= --format= -h --help -v --verbose --file-version -v --version --get-output-plugins"
set -l C000 "$query '$opts' positional_contains 2 hash && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins -f --format"
set -l C001 "$query '$opts' positional_contains 2 hash && not $query '$opts' has_option -h --help -v --verbose --file-version --version --get-output-plugins"
complete -c $prog -n $C000 -s f -l format -d 'Set output format' -x -a '(readpe --get-output-plugins)'
complete -c $prog -n $C001 -s h -l help -d 'Print this message' -f
complete -c $prog -n $C001 -s v -l verbose -d 'Print more verbose' -f

# vim: ft=fish ts=2 sts=2 sw=2 et
