.TH OFS2RVA 1
.SH NAME
ofs2rva - converts a PE raw file offset to relative virtual address

.SH SYNOPSIS
.B ofs2rva
.IR offset
.IR pefile

.SH DESCRIPTION
ofs2rva converts a raw file offset to RVA (Relative Virtual Address), if it's valid. It's part of pev, the PE file analysis toolkit.
.PP
\&\fIoffset\fR is a valid PE file offset in decimal or hexadecimal (prefixed with 0x).
.PP
\&\fIpefile\fR is a PE32/PE32+ executable or dynamic linked library file.

.SH OPTIONS

.TP
.BR \-V ", " \-\-version
Show version.

.TP
.BR \-\-help
Show this help.

.SH EXAMPLES
Get RVA of 0x1b9b8 offset of \fBcalc.exe\fP:
.IP
$ ofs2rva 0x1b9b8 calc.exe

.SH REPORTING BUGS
Please, check the latest development code and report at https://github.com/merces/pev/issues

.SH SEE ALSO
\fBpedis\fP(1), \fBpehash\fP(1), \fBpeldd\fP(1), \fBpepack\fP(1), \fBperes\fP(1), \fBpescan\fP(1), \fBpesec\fP(1), \fBpestr\fP(1), \fBreadpe\fP(1), \fBrva2ofs\fP(1)

.SH COPYRIGHT
Copyright (C) 2012 - 2020 pev authors. License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/gpl-2.0.txt>.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
rva2ofs(1)
