.TH PERES 1
.SH NAME
peres - analyze and extract PE file resources

.SH SYNOPSIS
.B peres
[OPTIONS]...
.IR pefile

.SH DESCRIPTION
peres opens the resource section of a PE file and it is able to show/extract resources.
.PP
\&\fIpefile\fR is a PE32/PE32+ executable or dynamic linked library file.

.SH OPTIONS
.TP
.BR \-a ", " \-\-all
show all information, statistics and extract resources.

.TP
.BR \-x ", " \-\-extract
extract resources.

.TP
.BR \-i ", " \-\-info
show resources information.

.TP
.BR \-s ", " \-\-statistics
show resource section statistics.

.TP
.BR \-v ", " \-\-version
show program version and exit.

.TP
.BR \-\-help
show help.

.SH EXAMPLES
Show resources statistics of \fBputty.exe\fP:
.IP
$ peres -s putty.exe

.SH REPORTING BUGS
Please, check the latest development code and report at https://github.com/merces/pev/issues

.SH COPYRIGHT
Copyright © 2013 pev authors. License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/gpl-2.0.txt>.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
