.TH PESCAN 1
.SH NAME
pescan - identify suspicious characteristcis in PE files

.SH SYNOPSIS
.B pescan
[OPTIONS]...
.IR pefile

.SH DESCRIPTION
pescan analyze a PE file statically to determine if it contains suspicious characteristics.
It's part of pev analysis toolkit.
.PP
\&\fIpefile\fR is a PE32/PE32+ executable or dynamic linked library file.

.SH OPTIONS
.TP
.BR \-f ", " \-\-format\ <text|csv|xml|html>
change output format (default is text).

.TP
.BR \-v ", " \-\-version
show program version and exit.

.TP
.BR \-\-help
show help.

.SH EXAMPLES
Search suspicious things in \fBputty.exe\fP:
.IP
$ pescan putty.exe

.SH REPORTING BUGS
Please, check the latest development code and report at at https://github.com/merces/pev/issues

.SH COPYRIGHT
Copyright © 2012 pev authors. Licensed GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
