.TH PESCAN 1
.SH NAME
pescan - identify suspicious characteristics in PE files

.SH SYNOPSIS
.B pescan
[OPTIONS]...
.IR pefile

.SH DESCRIPTION
pescan analyze a PE file statically to determine if it contains suspicious characteristics.
It's part of pev, the PE file analysis toolkit.
.PP
\&\fIpefile\fR is a PE32/PE32+ executable or dynamic linked library file.

.SH OPTIONS
.TP
.BR \-f ", " \-\-format\ <text|csv|xml|html>
Change output format (default is text).

.TP
.BR \-v ", " \-\-verbose
Show more information about found items.

.TP
.BR \-V ", " \-\-version
Show version.

.TP
.BR \-\-help
Show help.

.SH EXAMPLES
Search suspicious things in \fBputty.exe\fP:
.IP
$ pescan putty.exe

.SH REPORTING BUGS
Please, check the latest development code and report at https://github.com/merces/pev/issues

.SH SEE ALSO
\fBofs2rva\fP(1), \fBpedis\fP(1), \fBpehash\fP(1), \fBpeldd\fP(1), \fBpepack\fP(1), \fBperes\fP(1), \fBpesec\fP(1), \fBpestr\fP(1), \fBreadpe\fP(1), \fBrva2ofs\fP(1)

.SH COPYRIGHT
Copyright (C) 2013 - 2020 pev authors. License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/gpl-2.0.txt>.
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
